export const INSIGHTALL_OPENAI_IMAGE_PROVIDER_KEY = 'insightall-openai-image';
export const INSIGHTALL_OPENAI_IMAGE_DEFAULT_MODEL = 'gpt-image-2';
export const INSIGHTALL_OPENAI_IMAGE_DEFAULT_REF = `${INSIGHTALL_OPENAI_IMAGE_PROVIDER_KEY}/${INSIGHTALL_OPENAI_IMAGE_DEFAULT_MODEL}`;
