export const INSIGHTALLX_OPENAI_IMAGE_PROVIDER_KEY = 'insightallx-openai-image';
export const INSIGHTALLX_OPENAI_IMAGE_DEFAULT_MODEL = 'gpt-image-2';
export const INSIGHTALLX_OPENAI_IMAGE_DEFAULT_REF = `${INSIGHTALLX_OPENAI_IMAGE_PROVIDER_KEY}/${INSIGHTALLX_OPENAI_IMAGE_DEFAULT_MODEL}`;
